#
# Available repositories are listed here:
# https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
#

sudo: false

language:
  - cpp
  - python

python: 2.7

matrix:
    include:
        - env:
            - COMPILER_VERSION=4.8
            - ASAN=1
          os: linux
          compiler: g++
          addons:
            apt:
              sources: ubuntu-toolchain-r-test
              packages:
                 - g++-4.8
                 - gnupg
                 - cmake

        - env:
            - COMPILER_VERSION=4.9
            - ASAN=0
          os: linux
          compiler: g++
          addons:
            apt:
              sources: ubuntu-toolchain-r-test
              packages:
                - g++-4.9
                - gnupg
                - cmake

        - env:
            - COMPILER_VERSION=3.5
            - ASAN=1
          os: linux
          compiler: clang++
          addons:
            apt:
              sources:
                - llvm-toolchain-precise-3.5
                - ubuntu-toolchain-r-test
              packages:
                - clang-3.5
                - gnupg
                - cmake

        - env:
            - COMPILER_VERSION=3.6
            - SKIP_TESTS=On
            - ASAN=1
          os: linux
          compiler: clang++
          addons:
            apt:
              sources:
                - llvm-toolchain-precise-3.6
                - ubuntu-toolchain-r-test
              packages:
                - clang-3.6
                - gnupg
                - cmake
before_install:
    - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
    - sudo apt-get update

install:
  - pip install --user --upgrade nose
  - pip install --user --upgrade PyHamcrest

before_script:
    - mkdir build
    - cd build
    - echo "Using compilers $CXX-${COMPILER_VERSION} and $CC-${COMPILER_VERSION}"
    - cmake -DASAN=$ASAN -DCMAKE_CXX_COMPILER=$CXX-${COMPILER_VERSION} -DCMAKE_C_COMPILER=$CC-${COMPILER_VERSION} -DRTAGS_NO_ELISP_BYTECOMPILE=1 ..
    - cd ..

script:
    - VERBOSE=1 make -j2 -C build
    - sh -c 'if [ -z "$SKIP_TESTS" ]; then PATH=$(pwd)/build/bin:$PATH nosetests; else echo "Skipping tests for this platform."; fi'
