#
# Available repositories are listed here:
# https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
#

sudo: required
dist: trusty

language: cpp

git:
  depth: 3

matrix:
  include:
    - env: COMPILER_VERSION=5.1
      os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gnupg
    - env: COMPILER_VERSION=3.9
      os: linux
      compiler: clang++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages:
            - clang-3.8
            - gnupg

install:
  - pip install --user --upgrade nose
  - pip install --user --upgrade PyHamcrest

script: ./scripts/travis.sh
